# Generated by Django 5.0.2 on 2024-02-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_category_business_category_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='price_range',
            field=models.CharField(choices=[('$', 'Very Cheap'), ('$$', 'Cheap'), ('$$$', 'Moderate'), ('$$$', 'Expensive'), ('$$$', 'Very Expensive')], default='$$$', max_length=10),
        ),
    ]
