# Generated by Django 5.0.2 on 2024-02-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_business_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='price_range',
            field=models.CharField(choices=[('$', 'Very Cheap'), ('$$', 'Cheap'), ('$$$', 'Moderate'), ('$$$$', 'Expensive'), ('$$$$$', 'Very Expensive')], default='$$$', max_length=10),
        ),
    ]
