# Generated by Django 5.0.2 on 2024-02-13 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_business_slug_category_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='contry',
            new_name='country',
        ),
    ]
