# Generated by Django 5.0.2 on 2024-02-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_rename_url_business_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='starts',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
