# Generated by Django 5.0.2 on 2024-02-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_rename_starts_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
